from django.urls import path
from .views import (
    AssignmentListView,
    TopicListView,
    TopicNameListView,
    AssignAssignmentCreateView,
    StudentAssignedAssignmentsListView,
    AssignAssignmentGetAllStudentsView,
    AssignmentDetailView,
    SubmitAssignmentView,
    GetTopicsForStudentView,
    GetAssignedAssignmentsStudentView,
    GetAttemptedAssignmentView,
    GetStudentCompetencyReportView,
    GetTeksDetailsReportView,
    GetStudentGrowthByTeksView,
    GetAssignedAssignmentListView,
    AssignedAssignmentRetrieveUpdateDeleteView,
    GetWorksheetView,
    GetTestQuestionView,
)

urlpatterns = [
    path('topics/<int:topic_id>/', AssignmentListView.as_view(), name="assignments"),
    path('topics/<int:topic_id>/names/',
         AssignmentListView.as_view(), name="assignments"),
    path('classes/<int:class_id>/topics/',
         TopicListView.as_view(), name="topics"),
    path('classes/<int:class_id>/topics/names/',
         TopicNameListView.as_view(), name="topics"),
    path('assign',  AssignAssignmentCreateView.as_view(),
         name="assign-assignments"),
    path('my/assignments',  StudentAssignedAssignmentsListView.as_view(),
         name="my-assigned-assignments"),
    path("<int:assignment_id>/class/<int:class_id>/students/",
         AssignAssignmentGetAllStudentsView.as_view()),
    path("<int:pk>", AssignmentDetailView.as_view(),
         name="assignment-detail"),
    path("<int:assignment_id>/submit",
         SubmitAssignmentView.as_view(), name='submit-assignment'),
    path("students/me/topics", GetTopicsForStudentView.as_view(),
         name='topics-for-student'),
    path("students/topics/<topic_id>", GetAssignedAssignmentsStudentView.as_view(),
         name="assigned-assignments-of-student-by-topic"),
    path("students/me/attempted-assignments/<int:assignment_id>",
         GetAttemptedAssignmentView.as_view(), name="student-attempted-assignment-view"),
    path('reports/competencies/students/<student_id>/',
         GetStudentCompetencyReportView.as_view(), name="get-student-competency-report"),
    path('reports/teks/detail/classes/<int:class_id>',
         GetTeksDetailsReportView.as_view(), name="get-teks-detail-report"),
    path('reports/teks/growth/classes/<int:class_id>/students/<int:student_id>',
         GetStudentGrowthByTeksView.as_view(), name="get-student-growth-report-by-teks"),
    path('assigned/class/<int:class_id>', GetAssignedAssignmentListView.as_view(),
         name="get-all-assigned-assignment-groups"),
    path('assigned/class/<int:class_id>', GetAssignedAssignmentListView.as_view(),
         name="get-all-assigned-assignment-groups"),
    path('assigned/<int:assigned_assignment_id>', AssignedAssignmentRetrieveUpdateDeleteView.as_view(),
         name="get-update-delete-assigned-assignment"),
     path('<int:assignment_id>/worksheet',GetWorksheetView.as_view(),name="get-worksheet"),
     path('testquestion/<int:pk>',GetTestQuestionView.as_view()),
]
