# Generated by Django 4.0.4 on 2022-04-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacher_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='otp',
            field=models.CharField(default=440885, max_length=32),
        ),
    ]
