# Generated by Django 4.0.4 on 2022-04-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_teacher_otp_teacher_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='secret_key',
            field=models.CharField(default='OZGYVFGXQQXRYKB3V5NGGMS4RPBBH553', max_length=32),
        ),
    ]
