# Generated by Django 4.0.4 on 2022-04-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_teacher_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='secret_key',
            field=models.CharField(default='4OGYIZFUDWPIO3ZZ22TBVUTVJKOURCPH', max_length=32),
        ),
    ]
