# Generated by Django 4.0.4 on 2022-04-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_clas_alter_teacher_clas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='secret_key',
            field=models.CharField(default='XMYKHL6E4I4PHKBILACFUC7FTJ5DPC4R', max_length=32),
        ),
    ]
