# Generated by Django 4.0.4 on 2022-04-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_teacher_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='secret_key',
            field=models.CharField(default='FKOUYO5AMZGSJLZ5G2QLZSJDEDRVUA7X', max_length=32),
        ),
    ]
