# Generated by Django 4.0.4 on 2022-04-30 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_class_school_alter_class_teacher'),
        ('users', '0013_alter_teacher_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='clas',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.school'),
        ),
    ]
