# Generated by Django 4.0.4 on 2022-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='email'),
        ),
    ]
