# Generated by Django 4.0.4 on 2022-06-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='stripe_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
