# Generated by Django 4.0.4 on 2022-08-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_teacher_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='hassan', max_length=200),
            preserve_default=False,
        ),
    ]
