# Generated by Django 4.0.4 on 2022-12-01 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_requestedschool_requested_teacher'),
        ('users', '0021_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers', to='core.school'),
        ),
    ]
