# Generated by Django 4.0.4 on 2022-07-06 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paypal_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalCustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_customer_id', models.CharField(max_length=250)),
                ('subscription_status', models.CharField(choices=[('active', 'Assesment by TEKS'), ('canceled', 'Assesment by Skills'), ('expired', 'expired'), ('past due', 'Assesment by Work sheet'), ('pending', 'Assesment by Work sheet')], max_length=100, null=True)),
                ('local_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PaypalCustomer',
        ),
    ]
