# Generated by Django 4.0.4 on 2022-07-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payments', '0002_paypalcustomersubscription_delete_paypalcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalcustomersubscription',
            name='subscription_status',
        ),
    ]
