# Generated by Django 4.0.4 on 2022-07-06 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paypal_payments', '0003_remove_paypalcustomersubscription_subscription_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaypalCustomerSubscription',
            new_name='PaypalCustomer',
        ),
        migrations.CreateModel(
            name='PaypalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_subscription_id', models.CharField(max_length=255)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'expired'), ('past due', 'Past Due'), ('pending', 'Pending')], max_length=100, null=True)),
                ('local_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
