# Generated by Django 4.0.4 on 2022-04-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('grade_level', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third')], default='1', max_length=20)),
                ('no_of_students', models.IntegerField(default=30)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classes', to='core.school')),
            ],
        ),
    ]
