# Generated by Django 4.0.4 on 2022-04-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade_level',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eight'), ('9', 'Ninth'), ('10', 'Tenth'), ('11', 'Eleventh')], default='1', max_length=20),
        ),
    ]
