# Generated by Django 4.0.4 on 2022-07-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade'),
        ),
    ]
