# Generated by Django 4.0.4 on 2022-07-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_requestqoute'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestqoute',
            name='description',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
    ]
