# Generated by Django 4.0.4 on 2022-11-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_requestqoute_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
