# Generated by Django 4.0.4 on 2022-12-01 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_requestedschool_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedschool',
            name='requested_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
