# Generated by Django 4.0.4 on 2022-12-01 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_requestedschool_requested_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedschool',
            name='requested_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
