# Generated by Django 4.0.4 on 2022-06-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sripe_payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='starting_date',
        ),
    ]
