# Generated by Django 4.0.4 on 2022-05-31 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_student_email'),
        ('assignment', '0002_assignmentresultdetail_delete_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentresultdetail',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentresultdetail',
            name='student',
        ),
        migrations.CreateModel(
            name='AssignmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=3)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_details', to='assignment.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.student')),
            ],
        ),
    ]
