# Generated by Django 4.0.4 on 2022-05-31 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_student_email'),
        ('assignment', '0003_remove_assignmentresultdetail_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='result_details', to='assignment.assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='result_details', to='users.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assignment.assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='users.student'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='selected_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assignment.option'),
        ),
    ]
