# Generated by Django 4.0.4 on 2022-05-31 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignmentresultdetail_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assignment.option'),
        ),
    ]
