# Generated by Django 4.0.4 on 2022-06-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_alter_assignmentresultdetail_selected_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresult',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
