# Generated by Django 4.0.4 on 2022-06-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_alter_assignment__type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInBlankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='TextFieldForFillinBlankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sorting_number', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.fillinblankquestion')),
            ],
        ),
        migrations.CreateModel(
            name='OptionFieldForFillinBlankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('is_correct', models.BooleanField(default=False)),
                ('sorting_number', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.fillinblankquestion')),
            ],
        ),
    ]
