# Generated by Django 4.0.4 on 2022-06-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_sortingquestion_sortingquestionoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='worksheet',
            field=models.FileField(blank=True, null=True, upload_to='worksheets/'),
        ),
    ]
