# Generated by Django 4.0.4 on 2022-06-30 11:05

import assignment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_assignment_worksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='worksheet',
            field=models.FileField(blank=True, null=True, upload_to='worksheets/', validators=[assignment.validators.validate_pdf]),
        ),
    ]
