# Generated by Django 4.0.4 on 2022-07-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_alter_assignment_worksheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortingquestionoptions',
            name='is_correct',
        ),
    ]
