# Generated by Django 4.0.4 on 2022-07-07 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0014_remove_sortingquestionoptions_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortingquestion',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorting_questions', to='assignment.assignment'),
        ),
        migrations.AlterField(
            model_name='sortingquestionoptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assignment.sortingquestion'),
        ),
    ]
