# Generated by Django 4.0.4 on 2022-07-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0015_alter_sortingquestion_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillinblankquestion',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_in_blank_questions', to='assignment.assignment'),
        ),
        migrations.AlterField(
            model_name='optionfieldforfillinblankquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assignment.textfieldforfillinblankquestion'),
        ),
        migrations.AlterField(
            model_name='textfieldforfillinblankquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_fields', to='assignment.fillinblankquestion'),
        ),
    ]
