# Generated by Django 4.0.4 on 2022-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0017_alter_topic_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.CharField(max_length=250)),
            ],
        ),
    ]
