# Generated by Django 4.0.4 on 2022-07-12 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0019_calculatorquestion_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropDownQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='title')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_questions', to='assignment.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='DropDownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('dropdown_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assignment.dropdownquestion')),
            ],
        ),
    ]
