# Generated by Django 4.0.4 on 2022-07-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0020_dropdownquestion_dropdownoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortingquestionoptions',
            name='ordering_number',
        ),
        migrations.AddField(
            model_name='calculatorquestion',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='dropdownquestion',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
