# Generated by Django 4.0.4 on 2022-07-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0021_remove_sortingquestionoptions_ordering_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortingquestionoptions',
            name='correct_sorting_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
