# Generated by Django 4.0.4 on 2022-07-18 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_teacher_stripe_id'),
        ('assignment', '0022_sortingquestionoptions_correct_sorting_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentresultdetail',
            name='question',
        ),
        migrations.RemoveField(
            model_name='assignmentresultdetail',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='calculator_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.calculatorquestion'),
        ),
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='drop_down_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.dropdownquestion'),
        ),
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='drop_down_selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.dropdownoption'),
        ),
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='fill_in_the_blank_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.fillinblankquestion'),
        ),
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='fill_in_the_blank_question_selected_option',
            field=models.ManyToManyField(to='assignment.fillinblankquestion'),
        ),
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='mcq_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.question'),
        ),
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='mcq_selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.option'),
        ),
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='sorting_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.sortingquestion'),
        ),
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='sorting_question_selected_option',
            field=models.ManyToManyField(related_name='results', to='assignment.sortingquestionoptions'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_details', to='assignment.assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_details', to='users.student'),
        ),
    ]
