# Generated by Django 4.0.4 on 2022-07-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0023_remove_assignmentresultdetail_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='calculator_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.calculatorquestion'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='drop_down_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.dropdownquestion'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='drop_down_selected_option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.dropdownoption'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='fill_in_the_blank_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.fillinblankquestion'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='mcq_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.question'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='mcq_selected_option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.option'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='sorting_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='assignment.sortingquestion'),
        ),
    ]
