# Generated by Django 4.0.4 on 2022-07-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0024_alter_assignmentresultdetail_calculator_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='calculator_question_answer',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
