# Generated by Django 4.0.4 on 2022-07-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0025_assignmentresultdetail_calculator_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentresultdetail',
            old_name='sorting_question_selected_option',
            new_name='sorting_question_selected_options',
        ),
    ]
