# Generated by Django 4.0.4 on 2022-07-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0026_rename_sorting_question_selected_option_assignmentresultdetail_sorting_question_selected_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentresultdetail',
            name='fill_in_the_blank_question_selected_option',
        ),
    ]
