# Generated by Django 4.0.4 on 2022-07-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0027_remove_assignmentresultdetail_fill_in_the_blank_question_selected_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='sorting_question_selected_options',
            field=models.ManyToManyField(blank=True, null=True, related_name='results', to='assignment.sortingquestionoptions'),
        ),
    ]
