# Generated by Django 4.0.4 on 2022-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0029_alter_calculatorquestion_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='fill_in_the_blank_question_answers',
            field=models.ManyToManyField(blank=True, related_name='results', to='assignment.optionfieldforfillinblankquestion'),
        ),
        migrations.AddField(
            model_name='fillinblankquestion',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='sorting_question_selected_options',
            field=models.ManyToManyField(blank=True, related_name='results', to='assignment.sortingquestionoptions'),
        ),
    ]
