# Generated by Django 4.0.4 on 2022-07-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0030_assignmentresultdetail_fill_in_the_blank_question_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillinblankquestion',
            name='text',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
