# Generated by Django 4.0.4 on 2022-07-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0031_fillinblankquestion_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
