# Generated by Django 4.0.4 on 2022-08-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0033_testquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='McqQuestion',
        ),
    ]
