# Generated by Django 4.0.4 on 2022-08-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0034_rename_question_mcqquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='McqOption',
        ),
    ]
