# Generated by Django 4.0.4 on 2022-08-17 11:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0038_alter_dropdownquestion_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillinblankquestion',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='textfieldforfillinblankquestion',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
