# Generated by Django 4.0.4 on 2022-08-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0039_alter_fillinblankquestion_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillinblankquestion',
            name='text',
        ),
    ]
