# Generated by Django 4.0.4 on 2022-08-17 14:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0041_fractionmodel1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractionmodel1',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraction_model1_questions', to='assignment.assignment'),
        ),
        migrations.AlterField(
            model_name='sortingquestion',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
