# Generated by Django 4.0.4 on 2022-08-17 14:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0042_alter_fractionmodel1_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatorquestion',
            name='answer',
        ),
        migrations.CreateModel(
            name='CalculatorQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField()),
                ('calculator_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_answers', to='assignment.calculatorquestion')),
            ],
        ),
    ]
