# Generated by Django 4.0.4 on 2022-08-17 15:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0043_remove_calculatorquestion_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorquestion',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
