# Generated by Django 4.0.4 on 2022-08-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0044_alter_calculatorquestion_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentresultdetail',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='assignmentresultdetail',
            name='mcq_selected_option',
        ),
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='mcq_selected_options',
            field=models.ManyToManyField(blank=True, related_name='marked_options', to='assignment.mcqoption'),
        ),
    ]
