# Generated by Django 4.0.4 on 2022-08-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0045_remove_assignmentresultdetail_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentresult',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='calculatorquestion',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='fillinblankquestion',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='fractionmodel1',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='mcqquestion',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='sortingquestion',
            name='marks',
        ),
        migrations.AddField(
            model_name='assignment',
            name='marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='mcq_selected_options',
            field=models.ManyToManyField(blank=True, related_name='selected_options', to='assignment.mcqoption'),
        ),
    ]
