# Generated by Django 4.0.4 on 2022-08-18 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0046_remove_assignmentresult_total_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='fraction_model_1_answers',
            field=models.CharField(blank=True, default=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='assignmentresultdetail',
            name='fraction_model_1_question',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assignment.fractionmodel1'),
        ),
    ]
