# Generated by Django 4.0.4 on 2022-11-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_student_name'),
        ('assignment', '0047_assignmentresultdetail_fraction_model_1_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_details', to='assignment.assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='calculator_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assignment.calculatorquestion'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='drop_down_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assignment.dropdownquestion'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='drop_down_selected_option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assignment.dropdownoption'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='fill_in_the_blank_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assignment.fillinblankquestion'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='mcq_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assignment.mcqquestion'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='sorting_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assignment.sortingquestion'),
        ),
        migrations.AlterField(
            model_name='assignmentresultdetail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_details', to='users.student'),
        ),
    ]
